2023-12-15 18:01:29,274 DEBUG :: this is a debug log
2023-12-15 18:01:54,549 INFO :: this is a info log
2023-12-16 02:18:32,004 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:18:32,288 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:21:39,472 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:21:39,811 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:21:42,159 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:21:42,431 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:21:55,875 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:21:56,215 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:33:06,337 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:33:06,651 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:33:29,153 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:33:29,430 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:37:33,985 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:37:34,292 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:43:48,602 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:43:48,876 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:44:12,793 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:44:13,089 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:44:34,218 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:44:34,491 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:45:36,632 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:45:36,961 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-21 01:59:37,462 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 01:59:37,462 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89fc222470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:03:07,829 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:03:07,829 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba08cde470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:11:08,901 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:11:08,901 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb21dade3e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:12:34,216 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:12:34,216 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fed530de3e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:14:37,716 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:14:37,717 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc4582b6470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:17:51,661 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:17:51,661 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f933bde23e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:24:21,819 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: 'BinanceClient' object has no attribute 'session'
2023-12-21 02:26:13,186 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:26:13,186 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19cdb56470>: Failed to establish a new connection: [Errno 111] Connection refused')))
