2023-12-15 18:01:29,274 DEBUG :: this is a debug log
2023-12-15 18:01:54,549 INFO :: this is a info log
2023-12-16 02:18:32,004 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:18:32,288 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:21:39,472 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:21:39,811 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:21:42,159 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:21:42,431 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:21:55,875 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:21:56,215 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:33:06,337 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:33:06,651 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:33:29,153 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:33:29,430 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:37:33,985 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:37:34,292 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:43:48,602 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:43:48,876 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:44:12,793 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:44:13,089 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:44:34,218 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:44:34,491 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-16 02:45:36,632 DEBUG :: Starting new HTTPS connection (1): api.nobitex.ir:443
2023-12-16 02:45:36,961 DEBUG :: https://api.nobitex.ir:443 "GET /v2/orderbook/all HTTP/1.1" 200 None
2023-12-21 01:59:37,462 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 01:59:37,462 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89fc222470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:03:07,829 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:03:07,829 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba08cde470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:11:08,901 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:11:08,901 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb21dade3e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:12:34,216 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:12:34,216 ERROR :: Connection Error while making request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fed530de3e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:14:37,716 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:14:37,717 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc4582b6470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:17:51,661 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:17:51,661 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f933bde23e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-21 02:24:21,819 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: 'BinanceClient' object has no attribute 'session'
2023-12-21 02:26:13,186 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-21 02:26:13,186 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19cdb56470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2023-12-23 14:31:58,562 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-23 14:32:01,860 DEBUG :: https://fapi.binance.com:443 "GET /api/v3/exchangeInfo HTTP/1.1" 404 None
2023-12-23 14:33:42,430 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-23 14:33:44,403 DEBUG :: https://fapi.binance.com:443 "GET /api/v3/exchangeInfo HTTP/1.1" 404 None
2023-12-23 14:44:08,303 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-23 14:44:10,212 DEBUG :: https://fapi.binance.com:443 "GET /api/v3/exchangeInfo HTTP/1.1" 404 None
2023-12-23 14:44:24,110 DEBUG :: Starting new HTTPS connection (1): fapi.binance.com:443
2023-12-23 14:44:26,018 DEBUG :: https://fapi.binance.com:443 "GET /api/v3/exchangeInfo HTTP/1.1" 404 None
2023-12-23 14:57:25,041 DEBUG :: Starting new HTTPS connection (1): api.binance.com:443
2023-12-23 14:57:35,047 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f2923f7ac50>: Failed to resolve 'api.binance.com' ([Errno -3] Temporary failure in name resolution)"))
2023-12-23 15:00:02,028 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 15:00:08,556 DEBUG :: https://api.bybit.com:443 "GET /v2/public/symbols HTTP/1.1" 200 142841
2023-12-23 16:03:31,834 DEBUG :: Starting new HTTPS connection (1): api.binance.com:443
2023-12-23 16:03:41,845 ERROR :: Connection Error while making request to /api/v3/exchangeInfo: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f884e9b2c50>: Failed to resolve 'api.binance.com' ([Errno -3] Temporary failure in name resolution)"))
2023-12-23 16:09:07,462 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 16:09:09,216 DEBUG :: https://api.bybit.com:443 "GET /v2/public/symbols HTTP/1.1" 200 142841
2023-12-23 16:17:57,520 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 16:17:58,973 DEBUG :: https://api.bybit.com:443 "GET /v2/public/symbols HTTP/1.1" 200 142841
2023-12-23 16:19:32,817 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 16:19:33,847 DEBUG :: https://api.bybit.com:443 "GET /v2/public/symbols HTTP/1.1" 200 142841
2023-12-23 16:26:27,900 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 16:26:37,911 ERROR :: Connection Error while making request to /v2/public/symbols: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v2/public/symbols (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd194646d40>: Failed to resolve 'api.bybit.com' ([Errno -3] Temporary failure in name resolution)"))
2023-12-23 16:30:17,054 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 16:30:27,065 ERROR :: Connection Error while making request to /v2/public/symbols: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v2/public/symbols (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f47bb33ad40>: Failed to resolve 'api.bybit.com' ([Errno -3] Temporary failure in name resolution)"))
2023-12-23 16:35:11,392 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 16:35:12,310 DEBUG :: https://api.bybit.com:443 "GET /v2/public/symbols HTTP/1.1" 200 None
2023-12-23 20:52:11,300 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 20:52:12,714 DEBUG :: https://api.bybit.com:443 "GET /v2/public/symbols HTTP/1.1" 200 142841
2023-12-23 21:08:14,548 DEBUG :: Starting new HTTPS connection (1): api.bybit.com:443
2023-12-23 21:08:15,608 DEBUG :: https://api.bybit.com:443 "GET /v2/public/symbols HTTP/1.1" 200 None
